//Auth
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//meals 
export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST'
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS'
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE'
export const ADD_MEAL_REQUEST = 'ADD_MEAL_REQUEST'
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS'
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE'
export const UPDATE_MEAL_REQUEST = 'UPDATE_MEAL_REQUEST'
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS'
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE'
export const UPDATE_MEAL_FOOD_REQUEST = 'UPDATE_MEAL_FOOD_REQUEST'
export const UPDATE_MEAL_FOOD_SUCCESS = 'UPDATE_MEAL_FOOD_SUCCESS'
export const UPDATE_MEAL_FOOD_FAILURE = 'UPDATE_MEAL_FOOD_FAILURE'
export const REMOVE_MEAL_FOOD_REQUEST = 'REMOVE_MEAL_FOOD_REQUEST'
export const REMOVE_MEAL_FOOD_SUCCESS = 'REMOVE_MEAL_FOOD_SUCCESS'
export const REMOVE_MEAL_FOOD_FAILURE = 'REMOVE_MEAL_FOOD_FAILURE'


//preferences
export const FETCH_PREFERENCES_REQUEST = 'FETCH_PREFERENCES_REQUEST'
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS'
export const FETCH_PREFERENCES_FAILURE = 'FETCH_PREFERENCES_FAILURE'

export const UPDATE_PREFERENCES_REQUEST = 'UPDATE_PREFERENCES_REQUEST'
export const UPDATE_PREFERENCES_SUCCESS = 'UPDATE_PREFERENCES_SUCCESS'
export const UPDATE_PREFERENCES_FAILURE = 'UPDATE_PREFERENCES_FAILURE'


export const FETCH_MEALS_FOR_STATS_REQUEST = 'FETCH_MEALS_FOR_STATS_REQUEST'
export const FETCH_MEALS_FOR_STATS_SUCCESS = 'FETCH_MEALS_FOR_STATS_SUCCESS'
export const FETCH_MEALS_FOR_STATS_FAILURE = 'FETCH_MEALS_FOR_STATS_FAILURE'

export const FETCH_PREFERENCES_FOR_STATS_REQUEST = 'FETCH_PREFERENCES_FOR_STATS_REQUEST'
export const FETCH_PREFERENCES_FOR_STATS_SUCCESS = 'FETCH_PREFERENCES_FOR_STATS_SUCCESS'
export const FETCH_PREFERENCES_FOR_STATS_FAILURE = 'FETCH_PREFERENCES_FOR_STATS_FAILURE'

export const FETCH_FOOD_LIST_REQUEST = 'FETCH_FOOD_LIST_REQUEST'
export const FETCH_FOOD_LIST_SUCCESS = 'FETCH_FOOD_LIST_SUCCESS'
export const FETCH_FOOD_LIST_FAILURE = 'FETCH_FOOD_LIST_FAILURE'

export const CLEAR_FOOD_LIST = 'CLEAR_FOOD_LIST'

export const CHANGE_FOOD_LIST_FILTERS = 'CHANGE_FOOD_LIST_FILTERS'

export const FETCH_FOOD_DETAIL_REQUEST = 'FETCH_FOOD_DETAIL_REQUEST'
export const FETCH_FOOD_DETAIL_SUCCESS = 'FETCH_FOOD_DETAIL_SUCCESS'
export const FETCH_FOOD_DETAIL_FAILURE = 'FETCH_FOOD_DETAIL_FAILURE'

export const UPDATE_FOOD_REQUEST = 'UPDATE_FOOD_REQUEST'
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS'
export const UPDATE_FOOD_FAILURE = 'UPDATE_FOOD_FAILURE'

export const CLEAR_FOOD_DETAIL = 'CLEAR_FOOD_DETAIL'