//Auth
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


//preferences
export const FETCH_PREFERENCES_REQUEST = 'FETCH_PREFERENCES_REQUEST'
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS'
export const FETCH_PREFERENCES_FAILURE = 'FETCH_PREFERENCES_FAILURE'

export const UPDATE_PREFERENCES_REQUEST = 'UPDATE_PREFERENCES_REQUEST'
export const UPDATE_PREFERENCES_SUCCESS = 'UPDATE_PREFERENCES_SUCCESS'
export const UPDATE_PREFERENCES_FAILURE = 'UPDATE_PREFERENCES_FAILURE'


export const FETCH_MEALS_FOR_STATS_REQUEST = 'FETCH_MEALS_FOR_STATS_REQUEST'
export const FETCH_MEALS_FOR_STATS_SUCCESS = 'FETCH_MEALS_FOR_STATS_SUCCESS'
export const FETCH_MEALS_FOR_STATS_FAILURE = 'FETCH_MEALS_FOR_STATS_FAILURE'

export const FETCH_PREFERENCES_FOR_STATS_REQUEST = 'FETCH_PREFERENCES_FOR_STATS_REQUEST'
export const FETCH_PREFERENCES_FOR_STATS_SUCCESS = 'FETCH_PREFERENCES_FOR_STATS_SUCCESS'
export const FETCH_PREFERENCES_FOR_STATS_FAILURE = 'FETCH_PREFERENCES_FOR_STATS_FAILURE'

